title: Zhang Chi
description: My Personal Blog
author: Zhang Chi
logo: ./assets/cg_sr04_0101.bmp
github: https://github.com/BlueySky27
about: Graduate Student

baseurl: "https://blueysky27.github.io"
url: "https://blueysky27.github.io"

allowsearch: true

disqus_shortname: aboutashu
google_analytics: UA-72862926-1

share:


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]

theme: jekyll-theme-cayman
