title: Zhang Chi
description: My Personal Blog
author: Zhanf Chi
logo: /hcz-jekyll-blog/static/img/avatar.png
github: https://github.com/BlueySky27
about: Undergraduate Student

baseurl: "https://blueysky27.github.io"
url: "https://blueysky27.github.io"

allowsearch: true

disqus_shortname: aboutashu
google_analytics: UA-72862926-1

share:


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]

theme: jekyll-theme-cayman